import type { SkillRecord } from './content-hub';

export const DEFAULT_SKILLS: SkillRecord[] = [
  {
    id: 'default-react',
    name: 'React',
    nameAr: 'React',
    category: 'Websites & Frontend',
    categoryAr: 'المواقع والواجهات',
    description: 'Interactive websites, portfolio pages, reusable components, and client-side flows.',
    descriptionAr: 'مواقع تفاعلية، صفحات بورتفوليو، مكونات قابلة لإعادة الاستخدام، وتدفقات واجهة أمامية.',
    proficiency: 94,
    categoryOrder: 1,
    order: 1,
    featured: true,
  },
  {
    id: 'default-nextjs',
    name: 'Next.js',
    nameAr: 'Next.js',
    category: 'Websites & Frontend',
    categoryAr: 'المواقع والواجهات',
    description: 'SEO-friendly websites, routing, server rendering, and production-ready web apps.',
    descriptionAr: 'مواقع مناسبة لمحركات البحث، تنظيم الصفحات، عرض من السيرفر، وتطبيقات ويب جاهزة للإنتاج.',
    proficiency: 88,
    categoryOrder: 1,
    order: 2,
    featured: true,
  },
  {
    id: 'default-tailwind',
    name: 'Tailwind CSS',
    nameAr: 'Tailwind CSS',
    category: 'Websites & Frontend',
    categoryAr: 'المواقع والواجهات',
    description: 'Responsive interfaces, design systems, RTL layouts, and fast UI iteration.',
    descriptionAr: 'واجهات متجاوبة، أنظمة تصميم، تخطيطات RTL، وتنفيذ سريع للتصميمات.',
    proficiency: 92,
    categoryOrder: 1,
    order: 3,
    featured: true,
  },
  {
    id: 'default-flutter',
    name: 'Flutter',
    nameAr: 'Flutter',
    category: 'Mobile Apps',
    categoryAr: 'تطبيقات الموبايل',
    description: 'Cross-platform Android and iOS apps with clean screens, state, and API integration.',
    descriptionAr: 'تطبيقات Android و iOS بواجهات منظمة، إدارة حالة، وربط مع API.',
    proficiency: 86,
    categoryOrder: 2,
    order: 1,
    featured: true,
  },
  {
    id: 'default-dart',
    name: 'Dart',
    nameAr: 'Dart',
    category: 'Mobile Apps',
    categoryAr: 'تطبيقات الموبايل',
    description: 'Typed app logic, models, services, and maintainable Flutter architecture.',
    descriptionAr: 'منطق تطبيقات منظم، موديلات، خدمات، وهيكلة Flutter قابلة للصيانة.',
    proficiency: 84,
    categoryOrder: 2,
    order: 2,
  },
  {
    id: 'default-mobile-integrations',
    name: 'Mobile Integrations',
    nameAr: 'تكاملات الموبايل',
    category: 'Mobile Apps',
    categoryAr: 'تطبيقات الموبايل',
    description: 'Push notifications, media handling, forms, offline state, and API-driven screens.',
    descriptionAr: 'إشعارات، التعامل مع الملفات والصور، النماذج، العمل بدون اتصال، وشاشات مرتبطة بالـ API.',
    proficiency: 80,
    categoryOrder: 2,
    order: 3,
  },
  {
    id: 'default-admin-panels',
    name: 'Admin Panels',
    nameAr: 'لوحات التحكم',
    category: 'Dashboards & Panels',
    categoryAr: 'لوحات التحكم والداشبورد',
    description: 'Management dashboards for projects, content, users, settings, and operational workflows.',
    descriptionAr: 'لوحات لإدارة المشاريع، المحتوى، المستخدمين، الإعدادات، وتدفقات التشغيل.',
    proficiency: 92,
    categoryOrder: 3,
    order: 1,
    featured: true,
  },
  {
    id: 'default-crud-workflows',
    name: 'CRUD Workflows',
    nameAr: 'إدارة البيانات CRUD',
    category: 'Dashboards & Panels',
    categoryAr: 'لوحات التحكم والداشبورد',
    description: 'Create, edit, filter, search, sort, upload, and manage records inside real tools.',
    descriptionAr: 'إضافة وتعديل وبحث وفرز ورفع ملفات وإدارة سجلات داخل أدوات عملية.',
    proficiency: 90,
    categoryOrder: 3,
    order: 2,
  },
  {
    id: 'default-charts-analytics',
    name: 'Charts & Analytics',
    nameAr: 'الرسوم والتحليلات',
    category: 'Dashboards & Panels',
    categoryAr: 'لوحات التحكم والداشبورد',
    description: 'KPIs, reports, chart views, summaries, and operational insights.',
    descriptionAr: 'مؤشرات أداء، تقارير، رسوم بيانية، ملخصات، ورؤى تشغيلية.',
    proficiency: 84,
    categoryOrder: 3,
    order: 3,
  },
  {
    id: 'default-node-express',
    name: 'Node.js & Express',
    nameAr: 'Node.js و Express',
    category: 'Backend & APIs',
    categoryAr: 'الباك إند والـ API',
    description: 'HTTP APIs, server routes, middleware, validation, and production server logic.',
    descriptionAr: 'واجهات API، مسارات سيرفر، Middleware، تحقق من البيانات، ومنطق تشغيل للإنتاج.',
    proficiency: 86,
    categoryOrder: 4,
    order: 1,
    featured: true,
  },
  {
    id: 'default-typescript',
    name: 'TypeScript',
    nameAr: 'TypeScript',
    category: 'Backend & APIs',
    categoryAr: 'الباك إند والـ API',
    description: 'Typed frontend and backend code, safer contracts, and maintainable project structure.',
    descriptionAr: 'كود Frontend و Backend بأنواع واضحة، عقود بيانات آمنة، وهيكلة سهلة الصيانة.',
    proficiency: 90,
    categoryOrder: 4,
    order: 2,
    featured: true,
  },
  {
    id: 'default-rest-api',
    name: 'REST APIs',
    nameAr: 'REST APIs',
    category: 'Backend & APIs',
    categoryAr: 'الباك إند والـ API',
    description: 'API design, request handling, error states, pagination, filtering, and integration.',
    descriptionAr: 'تصميم API، معالجة الطلبات، حالات الخطأ، الصفحات، الفلاتر، والربط مع الخدمات.',
    proficiency: 84,
    categoryOrder: 4,
    order: 3,
  },
  {
    id: 'default-firebase-auth',
    name: 'Firebase Auth',
    nameAr: 'تسجيل الدخول عبر Firebase',
    category: 'Auth & Storage',
    categoryAr: 'تسجيل الدخول والتخزين',
    description: 'Login flows, protected dashboards, user sessions, roles, and secure access states.',
    descriptionAr: 'تسجيل دخول، حماية لوحات التحكم، جلسات مستخدمين، أدوار، وحالات وصول آمنة.',
    proficiency: 86,
    categoryOrder: 5,
    order: 1,
    featured: true,
  },
  {
    id: 'default-firestore',
    name: 'Firestore',
    nameAr: 'Firestore',
    category: 'Auth & Storage',
    categoryAr: 'تسجيل الدخول والتخزين',
    description: 'Realtime collections, content storage, rules-aware reads, and public/admin data models.',
    descriptionAr: 'Collections مباشرة، تخزين محتوى، قراءة تراعي القواعد، وموديلات بيانات عامة وإدارية.',
    proficiency: 86,
    categoryOrder: 5,
    order: 2,
    featured: true,
  },
  {
    id: 'default-cloud-storage',
    name: 'Cloud Storage',
    nameAr: 'التخزين السحابي',
    category: 'Auth & Storage',
    categoryAr: 'تسجيل الدخول والتخزين',
    description: 'Media uploads, image libraries, file previews, and reusable assets across pages.',
    descriptionAr: 'رفع ملفات، مكتبة صور، معاينات ملفات، وأصول قابلة لإعادة الاستخدام عبر الصفحات.',
    proficiency: 82,
    categoryOrder: 5,
    order: 3,
  },
  {
    id: 'default-linux-servers',
    name: 'Linux Servers',
    nameAr: 'سيرفرات Linux',
    category: 'Servers & Deployment',
    categoryAr: 'السيرفرات والنشر',
    description: 'Production builds, Node services, ports, process management, and deployment checks.',
    descriptionAr: 'Build للإنتاج، خدمات Node، البورتات، إدارة العمليات، وفحص النشر.',
    proficiency: 82,
    categoryOrder: 6,
    order: 1,
    featured: true,
  },
  {
    id: 'default-pm2',
    name: 'PM2',
    nameAr: 'PM2',
    category: 'Servers & Deployment',
    categoryAr: 'السيرفرات والنشر',
    description: 'Process restarts, environment updates, logs, uptime, and running Node apps reliably.',
    descriptionAr: 'إعادة تشغيل العمليات، تحديث البيئة، قراءة اللوجات، الاستقرار، وتشغيل تطبيقات Node بثبات.',
    proficiency: 78,
    categoryOrder: 6,
    order: 2,
  },
  {
    id: 'default-git-github',
    name: 'Git & GitHub',
    nameAr: 'Git و GitHub',
    category: 'Servers & Deployment',
    categoryAr: 'السيرفرات والنشر',
    description: 'Branching, commits, push/pull workflows, deployment handoff, and release tracking.',
    descriptionAr: 'الفروع، الكوميت، أوامر السحب والدفع، تسليم النشر، وتتبع الإصدارات.',
    proficiency: 88,
    categoryOrder: 6,
    order: 3,
  },
];
